### ISSUE TITLE
Some codes are unavailable

### ISSUE THREAD

**Issue by chouqin3** [GoldExcalibur/EdgeTrans4Mark#2]
For instance, some codes are unavailable. Could you fix them?

from core.inference import get_final_preds, get_final_preds_from_coords
from utils.transforms import flip_back, fliplr_joints, get_affine_transform, affine_transform
from utils.vis import save_batch_heatmaps, save_debug_images, save_batch_image_with_joints, save_batch_image_with_joints_and_gts
from utils.vis import save_batch_crops, save_batch_flows
from utils.utils import AverageMeter, AverageMeterSet, _print_name_value
from utils.utils import normalize_coords, ramp, get_theta_flow, get_gaussian_maps, get_grid
from utils.utils import transform_feats, resize_feats

**Comment by GoldExcalibur** [comment]
sorry for the bug, will try to fix it these days

**Comment by kaichennie** [comment]
from flow_vis import flow_to_color
there's also no file named 'flow_vis', could you upload them?
